### ISSUE TITLE
fw4c tianocore graphics console

### ISSUE THREAD

**Issue by ghost** [Dasharo/protectli-coreboot-legacy#9]
i sincerely appreciate all of the time to build coreboot support for protectli hardware, thank you.

i am opening an "issue" and asking for help on how to troubleshoot the missing UEFI graphics console for my "fw4c" coreboot.rom that is generated by "./build.sh fw4c".

**i am able to succesfully boot into my operating system from the coreboot.rom**, however, i do not get a bootsplash or option to edit firmware settings. The official rom works as normal, protectli_fw4c_v4.12.0.12.rom.

i used cbfstool to compare my build details with the official rom and do not see any obvious differences in regards to graphics (such as the framebuffer or vga bios).

please let me know if i need to provide specific logs or other details. i would greatly appreciate any feedback on how to troubleshoot. thank you for your time. 

unrelated note: i think the build.sh script could be updated for "fw4c". the fw2 and fw4 are SeaBios (i think the cbfstool lines are unnecessary for building fw4c).

**Comment by jhnkane** [comment]
and here is the output of my Tianocore build stage (from "./build.sh fw4c"):

build Tianocore 139c157403a43e70f42cf80afb7d27fa9e93678b
    Copying custom bootsplash image
    Including external LAN driver
    Including externally built iPXE
WORKSPACE: /home/coreboot/coreboot/payloads/external/tianocore/tianocore
EDK_TOOLS_PATH: /home/coreboot/coreboot/payloads/external/tianocore/tianocore/BaseTools
CONF_PATH: /home/coreboot/coreboot/payloads/external/tianocore/tianocore/Conf
Copying $EDK_TOOLS_PATH/Conf/build_rule.template
     to /home/coreboot/coreboot/payloads/external/tianocore/tianocore/Conf/build_rule.txt
Copying $EDK_TOOLS_PATH/Conf/tools_def.template
     to /home/coreboot/coreboot/payloads/external/tianocore/tianocore/Conf/tools_def.txt
Copying $EDK_TOOLS_PATH/Conf/target.template
     to /home/coreboot/coreboot/payloads/external/tianocore/tianocore/Conf/target.txt
build -q -s -a IA32 -a X64 -t COREBOOT -p UefiPayloadPkg/UefiPayloadPkg.dsc -b RELEASE  -D BOOTLOADER=COREBOOT -D PCIE_BASE=0xe0000000  -D SERIAL_TERMINAL=TRUE -D PS2_KEYBOARD_ENABLE=FALSE -D PLATFORM_BOOT_TIMEOUT=6 -D SHELL_TYPE=BUILD_SHELL -D USE_CBMEM_FOR_CONSOLE=FALSE -D SECURE_BOOT_ENABLE=FALSE -D SECURE_BOOT_DEFAULT_ENABLE=FALSE -D TPM_ENABLE=FALSE -D DISABLE_MTRR_PROGRAMMING=TRUE -D DASHARO_SYSTEM_FEATURES_ENABLE=FALSE -D BOOT_MENU_KEY=0x0015 -D SETUP_MENU_KEY=0x0008 -D LOAD_OPTION_ROMS=FALSE -D BOOTLOADER=COREBOOT -D VARIABLE_SUPPORT=SMMSTORE -D PERFORMANCE_MEASUREMENT_ENABLE=TRUE -D NETWORK_LAN_ROM=TRUE -D NETWORK_IPXE=TRUE --pcd gUefiPayloadPkgTokenSpaceGuid.PcdiPXEOptionName=LNetwork Boot and Utilities --pcd gDasharoSystemFeaturesTokenSpaceGuid.PcdDefaultNetworkBootEnable=TRUE --pcd gEfiMdeModulePkgTokenSpaceGuid.PcdConOutRow=0 --pcd gEfiMdeModulePkgTokenSpaceGuid.PcdConOutColumn=0 --pcd gEfiMdeModulePkgTokenSpaceGuid.PcdSetupConOutRow=0 --pcd gEfiMdeModulePkgTokenSpaceGuid.PcdSetupConOutColumn=0
----
i do not know if this could be related to my missing UEFI interface: "LOAD_OPTION_ROMS=FALSE"

**Comment by ghost** [comment]
and here is my output of Tianocore, "./build.sh fw4c":

build Tianocore 139c157403a43e70f42cf80afb7d27fa9e93678b
    Copying custom bootsplash image
    Including external LAN driver
    Including externally built iPXE
WORKSPACE: /home/coreboot/coreboot/payloads/external/tianocore/tianocore
EDK_TOOLS_PATH: /home/coreboot/coreboot/payloads/external/tianocore/tianocore/BaseTools
CONF_PATH: /home/coreboot/coreboot/payloads/external/tianocore/tianocore/Conf
Copying $EDK_TOOLS_PATH/Conf/build_rule.template
     to /home/coreboot/coreboot/payloads/external/tianocore/tianocore/Conf/build_rule.txt
Copying $EDK_TOOLS_PATH/Conf/tools_def.template
     to /home/coreboot/coreboot/payloads/external/tianocore/tianocore/Conf/tools_def.txt
Copying $EDK_TOOLS_PATH/Conf/target.template
     to /home/coreboot/coreboot/payloads/external/tianocore/tianocore/Conf/target.txt
build -q -s -a IA32 -a X64 -t COREBOOT -p UefiPayloadPkg/UefiPayloadPkg.dsc -b RELEASE  -D BOOTLOADER=COREBOOT -D PCIE_BASE=0xe0000000  -D SERIAL_TERMINAL=TRUE -D PS2_KEYBOARD_ENABLE=FALSE -D PLATFORM_BOOT_TIMEOUT=6 -D SHELL_TYPE=BUILD_SHELL -D USE_CBMEM_FOR_CONSOLE=FALSE -D SECURE_BOOT_ENABLE=FALSE -D SECURE_BOOT_DEFAULT_ENABLE=FALSE -D TPM_ENABLE=FALSE -D DISABLE_MTRR_PROGRAMMING=TRUE -D DASHARO_SYSTEM_FEATURES_ENABLE=FALSE -D BOOT_MENU_KEY=0x0015 -D SETUP_MENU_KEY=0x0008 -D LOAD_OPTION_ROMS=FALSE -D BOOTLOADER=COREBOOT -D VARIABLE_SUPPORT=SMMSTORE -D PERFORMANCE_MEASUREMENT_ENABLE=TRUE -D NETWORK_LAN_ROM=TRUE -D NETWORK_IPXE=TRUE --pcd gUefiPayloadPkgTokenSpaceGuid.PcdiPXEOptionName=LNetwork Boot and Utilities --pcd gDasharoSystemFeaturesTokenSpaceGuid.PcdDefaultNetworkBootEnable=TRUE --pcd gEfiMdeModulePkgTokenSpaceGuid.PcdConOutRow=0 --pcd gEfiMdeModulePkgTokenSpaceGuid.PcdConOutColumn=0 --pcd gEfiMdeModulePkgTokenSpaceGuid.PcdSetupConOutRow=0 --pcd gEfiMdeModulePkgTokenSpaceGuid.PcdSetupConOutColumn=0

----
"LOAD_OPTION_ROMS=FALSE" 

i replicate the issue using default config.protectli_fw4c from v4.12.0.12 and fw4_v4.0.12.x

and please understand i am asking for help (need brainpower). i spent time reading the available instructions and compared "config" and "revision" in roms.

"4. If the graphics console is required in UEFI payload, enable framebuffer initialization in coreboot.
   This could be done by enabling native graphics or using VGA BIOS option rom."
https://github.com/tianocore/edk2/blob/master/UefiPayloadPkg/BuildAndIntegrationInstructions.txt

**Comment by mkopec** [comment]
> "LOAD_OPTION_ROMS=FALSE"

This option relates to loading option ROMs from PCI devices. For example, plug-in graphics cards have such drivers, and in that case you would need to set this option to TRUE.

However with integrated graphics, the Intel UEFI graphics driver is integrated into the firmware, so this option is not needed.

Can you confirm if the same issue happens with a different display?

**Comment by jhnkane** [comment]
> This option relates to loading option ROMs from PCI devices. For example, plug-in graphics cards have such drivers, and in that case you would need to set this option to TRUE.
However with integrated graphics, the Intel UEFI graphics driver is integrated into the firmware, so this option is not needed.

i understand, thank you for the explanation

--
> Can you confirm if the same issue happens with a different display?

yes, the same issue on two different monitors. benq 24.5" and viewsonic  24” with default protectli bootsplash.bmp , 1024x768. 
i do not see a mention of "bgrt" with dmesg. (the git HEAD message stands out, "use smalelr logo and bump to v4.12.0.12").
and i do not experience the same trouble on either display with protectli_fw4c_v4.12.0.12.rom.

--
please see attached, "**work.txt**", for my full build process.

Linux station 6.8.0-45-generic #45~22.04.1-Ubuntu

git clone https://github.com/dasharo/protectli-coreboot-legacy.git && cd protectli-coreboot-legacy

HEAD is now at c82e0e111a configs/config.protectli_fw4c: use smalelr logo and bump to v4.12.0.12
user@station ~/protectli-coreboot-legacy $ cp -r ~/protectli 3rdparty/blobs/mainboard/
user@station ~/protectli-coreboot-legacy $ ./build.sh fw4c

"3rdparty/blobs/mainboard/protectli" follows the script's expected structure (original files pulled with cbfstool for vbt.bin and ifdtool -x).

the config and revision are identical between my build and the protectli rom. i must be missing something ; (
[work.txt](https://github.com/user-attachments/files/17251162/work.txt)
![build_fw4c](https://github.com/user-attachments/assets/e2466a31-46cf-42f0-9a5a-b62bd1492d2a)

**Comment by jhnkane** [comment]
> This option relates to loading option ROMs from PCI devices. For example, plug-in graphics cards have such drivers, and in that case you would need to set this option to TRUE.
However with integrated graphics, the Intel UEFI graphics driver is integrated into the firmware, so this option is not needed.

i understand, thank you for the explanation

--
> Can you confirm if the same issue happens with a different display?

yes, the same issue on two different monitors, benq 24.5" and viewsonic 24” with default bootsplash.bmp , 1024x768. 
i do not see "bgrt" in dmesg (noting because the below git HEAD message stands out, "use smalelr logo and bump to v4.12.0.12").
and i do not experience the same trouble on either display with protectli_fw4c_v4.12.0.12.rom.

--
please see attached, "**work.txt**", for my full build process (Linux station 6.8.0-45-generic #45~22.04.1-Ubuntu).
[work.txt](https://github.com/user-attachments/files/17251288/work.txt)

git clone https://github.com/dasharo/protectli-coreboot-legacy.git && cd protectli-coreboot-legacy
git checkout v4.12.0.12
HEAD is now at c82e0e111a configs/config.protectli_fw4c: use smalelr logo and bump to v4.12.0.12
cp -r ~/protectli 3rdparty/blobs/mainboard/protectli
./build.sh fw4c

my folder copy matches the script's expected structure (original files pulled with cbfstool for vbt.bin and ifdtool -x).

config and revision are identical between my build and the protectli rom. i must be missing something ; (

![build_fw4c](https://github.com/user-attachments/assets/440fa7e7-7eb4-409b-ad77-68399524a97e)

**Comment by ghost** [comment]
> This option relates to loading option ROMs from PCI devices. For example, plug-in graphics cards have such drivers, and in that case you would need to set this option to TRUE.
However with integrated graphics, the Intel UEFI graphics driver is integrated into the firmware, so this option is not needed.

i understand, thank you for the explanation

--
> Can you confirm if the same issue happens with a different display?

yes, the same issue on two different monitors, benq 24.5" and viewsonic 24” with default bootsplash.bmp , 1024x768. 

--

i have a feeling that i missed something and would like to keep trying. i will report back with an update. 
thanks again for your response.

**Comment by ghost** [comment]
is there an obvious mistake in my process?

ubuntu-22.04.5
`uname -a
Linux fw4c 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

`docker run hello-world`
`git clone https://github.com/Dasharo/protectli-coreboot-legacy.git && cd protectli-coreboot-legacy/`
`git submodule update --init --checkout --recursive`
edit build.sh, comment out cbfstool lines, 115-131 (fw4c only)
`./build.sh fw4c`
`sudo flashrom -p internal --ifd -i bios -w protectli_fw4c_v4.12.0.12.rom`
*pull the plug*
no bootsplash, no efi graphic menu options, and no grub gfx. graphics only load with linux boot.
[revision.txt](https://github.com/user-attachments/files/17265106/revision.txt)

and same results with "git checkout v4.12.0.12".

**Comment by ghost** [comment]
"config.protectli_fw4c" must be using HDMI 2 for tianocore graphic output

maybe there are redundent options but **the below resolved my issue**:

comment out # CONFIG_ONBOARD_VGA_IS_PRIMARY=y
.# CONFIG_ONBOARD_VGA_IS_PRIMARY is not set

comment out # CONFIG_VGA_BIOS=y
.# CONFIG_VGA_BIOS is not set

comment out # CONFIG_FRAMEBUFFER_SET_VESA_MODE=y

CONFIG_RUN_FSP_GOP=y
CONFIG_HAVE_LINEAR_FRAMEBUFFER=y
CONFIG_INTEL_GMA_HAVE_VBT=y
CONFIG_INTEL_GMA_ADD_VBT=y
CONFIG_INTEL_GMA_VBT_FILE="src/mainboard/protectli/vault_bsw/variants/fw4c/data.vbt"

--

**Comment by jhnkane** [comment]
wow , i somehow managed to find and resolve the issue when building "fw4c" 🥇 
 
the issue was not the Tianocore build as my comments above had been focused on.

"config.protectli_fw4c" must be wrong for Tianocore UEFI. a copy/paste or merge issue with the other SeaBios variants (fw2 and 4b)?

and maybe some options are redundent but the below resolved my issue:

comment out # CONFIG_ONBOARD_VGA_IS_PRIMARY=y
comment out # CONFIG_VGA_BIOS=y
comment out # CONFIG_FRAMEBUFFER_SET_VESA_MODE=y
CONFIG_INTEL_GMA_HAVE_VBT=y
CONFIG_INTEL_GMA_ADD_VBT=y
CONFIG_INTEL_GMA_VBT_FILE="src/mainboard/protectli/vault_bsw/variants/fw4c/data.vbt"
CONFIG_VGA_ROM_RUN=n
CONFIG_RUN_FSP_GOP=y
CONFIG_DRIVERS_EFI_VARIABLE_STORE=y
CONFIG_SMMSTORE_V2=y

--

i still can not understand why the official rom works as normal when that same rom's embedded config seems incompatible with Tianocore. 
***exploding head***

i am a git noob and do not know how to contribute to the protectli-coreboot-legacy project but this was fun lol : )

@mkopec , please let me know if I need to update my issue to closed or if you have questions for me, thank you.

**Comment by ghost** [comment]
i missed the reasons that were already documented on "CHANGELOG.md". thankyou.
